### PR TITLE
Use inline-buttons instead of simple text replies

### PR DESCRIPTION
**Pull request by daemon1024**

### CODE REVIEW

**Comment by sidntrivedi** [comment]
@daemon1024 Thanks for the PR. 🎉  The changes LGTM. 

Just one thing, please change the blog link to https://osdcblog.netlify.com. Also, did you use the Go extension of VSCode/any text editor you use ? It can help in better indentation if you have not used it yet.

 Thanks. 👍

**Comment by daemon1024** [comment]
> @daemon1024 Thanks for the PR.  The changes LGTM.
>
Great.

> Just one thing, please change the blog link to https://osdcblog.netlify.com. 

Done

>Also, did you use the Go extension of VSCode/any text editor you use ? It can help in better indentation if you have not used it yet.
>
I did use the Go extension in VSCode. I removed some extra blank lines if that makes it look somewhat better :)
> 
> Thanks.

:smiley:

**Comment by sidntrivedi** [comment]
@daemon1024 Cool. Fine by me.

@vaibhavk Wdyt?

**Comment by vnzongzna** [comment]
@daemon1024 I see a lot of repeated code here, not that it's bad but it can still be improved to a more readable one if you can move that in a separate function. WDYT?

**Comment by daemon1024** [comment]
> @daemon1024 I see a lot of repeated code here, not that it's bad but it can still be improved to a more readable one if you can move that in a separate function. WDYT?

How does this look? Made a function "ButtonLinks" for the repeated code. Ig will also make it easy to add more buttons in future.

**Pull request merged**
